[package]
name = "autosway"
version = "0.1.0"
authors = ["mzanibelli <mzanibelli@gmail.com>"]
edition = "2018"

[dependencies]
serde =  { version = "", features = ["derive"] }
serde_json = ""
sha2 = ""
tempfile = ""
